services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ..:/online-store  
    environment:
      - DEBUG=False
    command: /runservers.sh